config/routes.rb
Rails.application.routes.draw do
  resources :reports, :as => :xucf_reports, :controller => :xucf_reports
  resources :class_courses, :as => :xucf_class_courses, :controller => :xucf_class_courses
  resources :courses, :as => :xucf_courses, :controller => :xucf_courses do
    member do
      get 'grade/:grade_id', :action => 'grade'
    end
  end
  resources :teachers, :as => :xucf_teachers, :controller => :xucf_teachers do
    member do
      get :courses
    end
  end
  resources :classes, :as => :xucf_classes, :controller => :xucf_classes do
    resources :students, :as => :xucf_students, :controller => :xucf_students do
      member do
        get :scores
        get :courses
        get 'term/:term_id', :action => 'term'
      end
    end
    member do
      get :courses
    end
  end
  resources :majors, :as => :xucf_majors, :controller => :xucf_majors do
    member do
      get 'rank/:grade_id', :action => 'rank'
    end
  end

end

app/models/xucf_teacher.rb
class XucfTeacher < ActiveRecord::Base
  belongs_to :xucf_college
end

app/controllers/xucf_teachers_controller.rb
class XucfTeachersController < ApplicationController
  before_action :set_xucf_teacher, only: [:show, :edit, :update, :destroy]

  def courses
    courses = XucfClassCourse.where( :xucf_teacher_id => params[:id] )
    @named_courses = []
    courses.each do |ccourse|
      course = XucfCourse.where( :id => ccourse[:xucf_course_id] ).first
      klass = XucfClass.where( :id => ccourse[:xucf_class_id] ).first
      @named_courses << { course_name: course[:xcf_name], class_no: klass[:xcf_no], term: ccourse[:xcf_term] }
    end
    respond_to do |format|
      format.json { render :json => @named_courses }
    end
  end

  # GET /xucf_teachers
  # GET /xucf_teachers.json
  def index
    @xucf_teachers = XucfTeacher.all
  end

  # GET /xucf_teachers/1
  # GET /xucf_teachers/1.json
  def show
  end

  # GET /xucf_teachers/new
  def new
    @xucf_teacher = XucfTeacher.new
  end

  # GET /xucf_teachers/1/edit
  def edit
  end

  # POST /xucf_teachers
  # POST /xucf_teachers.json
  def create
    @xucf_teacher = XucfTeacher.new(xucf_teacher_params)

    respond_to do |format|
      if @xucf_teacher.save
        format.html { redirect_to @xucf_teacher, notice: 'Xucf teacher was successfully created.' }
        format.json { render :show, status: :created, location: @xucf_teacher }
      else
        format.html { render :new }
        format.json { render json: @xucf_teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /xucf_teachers/1
  # PATCH/PUT /xucf_teachers/1.json
  def update
    respond_to do |format|
      if @xucf_teacher.update(xucf_teacher_params)
        format.html { redirect_to @xucf_teacher, notice: 'Xucf teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @xucf_teacher }
      else
        format.html { render :edit }
        format.json { render json: @xucf_teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /xucf_teachers/1
  # DELETE /xucf_teachers/1.json
  def destroy
    @xucf_teacher.destroy
    respond_to do |format|
      format.html { redirect_to xucf_teachers_url, notice: 'Xucf teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_xucf_teacher
      @xucf_teacher = XucfTeacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def xucf_teacher_params
      params.require(:xucf_teacher).permit(:xcf_no, :xcf_name, :xucf_college_id, :xcf_gender, :xcf_birthyear, :xcf_title, :xcf_tel)
    end
end

app/helpers/xucf_teachers_helper.rb
module XucfTeachersHelper
end

app/views/xucf_teachers/_form.html.erb
<%= form_for(@xucf_teacher) do |f| %>
  <% if @xucf_teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@xucf_teacher.errors.count, "error") %> prohibited this xucf_teacher from being saved:</h2>

      <ul>
      <% @xucf_teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :xcf_no %><br>
    <%= f.text_field :xcf_no %>
  </div>
  <div class="field">
    <%= f.label :xcf_name %><br>
    <%= f.text_field :xcf_name %>
  </div>
  <div class="field">
    <%= f.label :xucf_college_id %><br>
    <%= f.number_field :xucf_college_id %>
  </div>
  <div class="field">
    <%= f.label :xcf_gender %><br>
    <%= f.text_field :xcf_gender %>
  </div>
  <div class="field">
    <%= f.label :xcf_birthyear %><br>
    <%= f.text_field :xcf_birthyear %>
  </div>
  <div class="field">
    <%= f.label :xcf_title %><br>
    <%= f.text_field :xcf_title %>
  </div>
  <div class="field">
    <%= f.label :xcf_tel %><br>
    <%= f.text_field :xcf_tel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/xucf_teachers/edit.html.erb
<h1>Editing Xucf Teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @xucf_teacher %> |
<%= link_to 'Back', xucf_teachers_path %>

app/views/xucf_teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Xucf Teachers</h1>

<table>
  <thead>
    <tr>
      <th>Xcf no</th>
      <th>Xcf name</th>
      <th>Xcf college</th>
      <th>Xcf gender</th>
      <th>Xcf birthyear</th>
      <th>Xcf title</th>
      <th>Xcf tel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @xucf_teachers.each do |xucf_teacher| %>
      <tr>
        <td><%= xucf_teacher.xcf_no %></td>
        <td><%= xucf_teacher.xcf_name %></td>
        <td><%= xucf_teacher.xucf_college_id %></td>
        <td><%= xucf_teacher.xcf_gender %></td>
        <td><%= xucf_teacher.xcf_birthyear %></td>
        <td><%= xucf_teacher.xcf_title %></td>
        <td><%= xucf_teacher.xcf_tel %></td>
        <td><%= link_to 'Show', xucf_teacher %></td>
        <td><%= link_to 'Edit', edit_xucf_teacher_path(xucf_teacher) %></td>
        <td><%= link_to 'Destroy', xucf_teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Xucf teacher', new_xucf_teacher_path %>

app/views/xucf_teachers/new.html.erb
<h1>New Xucf Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', xucf_teachers_path %>

app/views/xucf_teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Xcf no:</strong>
  <%= @xucf_teacher.xcf_no %>
</p>

<p>
  <strong>Xcf name:</strong>
  <%= @xucf_teacher.xcf_name %>
</p>

<p>
  <strong>Xcf college:</strong>
  <%= @xucf_teacher.xucf_college_id %>
</p>

<p>
  <strong>Xcf gender:</strong>
  <%= @xucf_teacher.xcf_gender %>
</p>

<p>
  <strong>Xcf birthyear:</strong>
  <%= @xucf_teacher.xcf_birthyear %>
</p>

<p>
  <strong>Xcf title:</strong>
  <%= @xucf_teacher.xcf_title %>
</p>

<p>
  <strong>Xcf tel:</strong>
  <%= @xucf_teacher.xcf_tel %>
</p>

<%= link_to 'Edit', edit_xucf_teacher_path(@xucf_teacher) %> |
<%= link_to 'Back', xucf_teachers_path %>