config/routes.rb
Rails.application.routes.draw do
  resources :reports, :as => :xucf_reports, :controller => :xucf_reports
  resources :class_courses, :as => :xucf_class_courses, :controller => :xucf_class_courses
  resources :courses, :as => :xucf_courses, :controller => :xucf_courses do
    member do
      get 'grade/:grade_id', :action => 'grade'
    end
  end
  resources :teachers, :as => :xucf_teachers, :controller => :xucf_teachers do
    member do
      get :courses
    end
  end
  resources :classes, :as => :xucf_classes, :controller => :xucf_classes do
    resources :students, :as => :xucf_students, :controller => :xucf_students do
      member do
        get :scores
        get :courses
        get 'term/:term_id', :action => 'term'
      end
    end
    member do
      get :courses
    end
  end
  resources :majors, :as => :xucf_majors, :controller => :xucf_majors do
    member do
      get 'rank/:grade_id', :action => 'rank'
    end
  end

end

app/models/xucf_major.rb
class XucfMajor < ActiveRecord::Base
  belongs_to :xucf_college
  has_many :xucf_classes
end

app/controllers/xucf_majors_controller.rb
class XucfMajorsController < ApplicationController
  before_action :set_xucf_major, only: [:show, :edit, :update, :destroy]

  def rank
    classes = XucfClass.where( :xucf_major => params[:id], :xcf_grade => params[:grade_id] )
    class_ids = []
    classes.each do |klass|
      class_ids << klass[:id]
    end
    @students = XucfStudent.where(:xucf_class_id => class_ids).order("xcf_credit DESC")
    respond_to do |format|
      format.json { render :json => @students }
    end
  end

  # GET /xucf_majors
  # GET /xucf_majors.json
  def index
    @xucf_majors = XucfMajor.all
  end

  # GET /xucf_majors/1
  # GET /xucf_majors/1.json
  def show
  end

  # GET /xucf_majors/new
  def new
    @xucf_major = XucfMajor.new
  end

  # GET /xucf_majors/1/edit
  def edit
  end

  # POST /xucf_majors
  # POST /xucf_majors.json
  def create
    @xucf_major = XucfMajor.new(xucf_major_params)

    respond_to do |format|
      if @xucf_major.save
        format.html { redirect_to @xucf_major, notice: 'Xucf major was successfully created.' }
        format.json { render :show, status: :created, location: @xucf_major }
      else
        format.html { render :new }
        format.json { render json: @xucf_major.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /xucf_majors/1
  # PATCH/PUT /xucf_majors/1.json
  def update
    respond_to do |format|
      if @xucf_major.update(xucf_major_params)
        format.html { redirect_to @xucf_major, notice: 'Xucf major was successfully updated.' }
        format.json { render :show, status: :ok, location: @xucf_major }
      else
        format.html { render :edit }
        format.json { render json: @xucf_major.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /xucf_majors/1
  # DELETE /xucf_majors/1.json
  def destroy
    @xucf_major.destroy
    respond_to do |format|
      format.html { redirect_to xucf_majors_url, notice: 'Xucf major was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_xucf_major
      @xucf_major = XucfMajor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def xucf_major_params
      params.require(:xucf_major).permit(:xcf_name, :xucf_college_id)
    end
end

app/helpers/xucf_majors_helper.rb
module XucfMajorsHelper
end

app/views/xucf_majors/_form.html.erb
<%= form_for(@xucf_major) do |f| %>
  <% if @xucf_major.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@xucf_major.errors.count, "error") %> prohibited this xucf_major from being saved:</h2>

      <ul>
      <% @xucf_major.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :xcf_name %><br>
    <%= f.text_field :xcf_name %>
  </div>
  <div class="field">
    <%= f.label :xucf_college_id %><br>
    <%= f.number_field :xucf_college_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/xucf_majors/edit.html.erb
<h1>Editing Xucf Major</h1>

<%= render 'form' %>

<%= link_to 'Show', @xucf_major %> |
<%= link_to 'Back', xucf_majors_path %>

app/views/xucf_majors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Xucf Majors</h1>

<table>
  <thead>
    <tr>
      <th>Xcf name</th>
      <th>Xcf college</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @xucf_majors.each do |xucf_major| %>
      <tr>
        <td><%= xucf_major.xcf_name %></td>
        <td><%= xucf_major.xucf_college_id %></td>
        <td><%= link_to 'Show', xucf_major %></td>
        <td><%= link_to 'Edit', edit_xucf_major_path(xucf_major) %></td>
        <td><%= link_to 'Destroy', xucf_major, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Xucf major', new_xucf_major_path %>

app/views/xucf_majors/new.html.erb
<h1>New Xucf Major</h1>

<%= render 'form' %>

<%= link_to 'Back', xucf_majors_path %>

app/views/xucf_majors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Xcf name:</strong>
  <%= @xucf_major.xcf_name %>
</p>

<p>
  <strong>Xcf college:</strong>
  <%= @xucf_major.xucf_college_id %>
</p>

<%= link_to 'Edit', edit_xucf_major_path(@xucf_major) %> |
<%= link_to 'Back', xucf_majors_path %>