config/routes.rb
Rails.application.routes.draw do
  resources :reports, :as => :xucf_reports, :controller => :xucf_reports
  resources :class_courses, :as => :xucf_class_courses, :controller => :xucf_class_courses
  resources :courses, :as => :xucf_courses, :controller => :xucf_courses do
    member do
      get 'grade/:grade_id', :action => 'grade'
    end
  end
  resources :teachers, :as => :xucf_teachers, :controller => :xucf_teachers do
    member do
      get :courses
    end
  end
  resources :classes, :as => :xucf_classes, :controller => :xucf_classes do
    resources :students, :as => :xucf_students, :controller => :xucf_students do
      member do
        get :scores
        get :courses
        get 'term/:term_id', :action => 'term'
      end
    end
    member do
      get :courses
    end
  end
  resources :majors, :as => :xucf_majors, :controller => :xucf_majors do
    member do
      get 'rank/:grade_id', :action => 'rank'
    end
  end

end

app/models/xucf_student.rb
class XucfStudent < ActiveRecord::Base
  belongs_to :xucf_class
  has_many :xucf_reports
  has_many :xucf_courses, :through => :xucf_reports
end

app/controllers/xucf_students_controller.rb
class XucfStudentsController < ApplicationController
  before_action :set_xucf_student, only: [:show, :edit, :update, :destroy]
  before_action :find_class

  def courses
    @courses = XucfCourse.joins( :xucf_reports ).where( "xucf_reports.xucf_student_id = ?", params[:id] )
    respond_to do |format|
      format.json { render :json => @courses }
    end
  end

  def scores
    reports = XucfReport.where( :xucf_student_id => params[:id] )
    @named_reports = []
    reports.each do |report|
      course = XucfCourse.find(report[:xucf_course_id])
      @named_reports << { course_name: course[:xcf_name], credit: course[:xcf_credit], score: report[:xcf_score] }
    end
    respond_to do |format|
      format.json { render :json => @named_reports }
    end
  end

  def term
    courses = XucfClassCourse.where( :xcf_term => params[:term_id], :xucf_class_id => params[:xucf_class_id] )
    term_reports = []
    courses.each do |course|
      course_detail = XucfCourse.find(course[:id])
      report = XucfReport.where( :xucf_student_id => params[:id], :xucf_course_id => course[:id] ).first
      if report
        term_reports << { course_name: course_detail[:xcf_name], credit: course_detail[:xcf_credit], score: report[:xcf_score] }
      else
        term_reports << { course_name: course_detail[:xcf_name], credit: course_detail[:xcf_credit], score: 0 }
      end
    end
    respond_to do |format|
      format.json { render :json => term_reports }
    end

  end

  # GET /xucf_students
  # GET /xucf_students.json
  def index
    @xucf_students = XucfStudent.all
  end

  # GET /xucf_students/1
  # GET /xucf_students/1.json
  def show
  end

  # GET /xucf_students/new
  def new
    @xucf_student = XucfStudent.new
  end

  # GET /xucf_students/1/edit
  def edit
  end

  # POST /xucf_students
  # POST /xucf_students.json
  def create
    @xucf_student = XucfStudent.new(xucf_student_params)

    respond_to do |format|
      if @xucf_student.save
        format.html { redirect_to @xucf_student, notice: 'Xucf student was successfully created.' }
        format.json { render :show, status: :created, location: @xucf_student }
      else
        format.html { render :new }
        format.json { render json: @xucf_student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /xucf_students/1
  # PATCH/PUT /xucf_students/1.json
  def update
    respond_to do |format|
      if @xucf_student.update(xucf_student_params)
        format.html { redirect_to xucf_class_xucf_student_path(@xucf_class, @xucf_student), notice: 'Student info was successfully updated.' }
        format.json { render :show, status: :ok, location: @xucf_student }
      else
        format.html { render :edit }
        format.json { render json: @xucf_student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /xucf_students/1
  # DELETE /xucf_students/1.json
  def destroy
    @xucf_student.destroy
    respond_to do |format|
      format.html { redirect_to xucf_students_url, notice: 'Xucf student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_xucf_student
      @xucf_student = XucfStudent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def xucf_student_params
      params.require(:xucf_student).permit(:xcf_no, :xcf_name, :xucf_class_id, :xcf_gender, :xcf_birthyear, :xcf_birthplace, :xcf_credit)
    end

    def find_class
      @xucf_class = XucfClass.find(params[:xucf_class_id])
    end

end

app/helpers/xucf_students_helper.rb
module XucfStudentsHelper
end

app/views/xucf_students/_form.html.erb
<%= form_for(@xucf_student, :url => xucf_class_xucf_student_path(@xucf_class, @xucf_student)) do |f| %>
  <% if @xucf_student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@xucf_student.errors.count, "error") %> prohibited this xucf_student from being saved:</h2>

      <ul>
      <% @xucf_student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :xcf_no %><br>
    <%= f.text_field :xcf_no %>
  </div>
  <div class="field">
    <%= f.label :xcf_name %><br>
    <%= f.text_field :xcf_name %>
  </div>
  <div class="field">
    <%= f.label :xucf_class_id %><br>
    <%= f.number_field :xucf_class_id %>
  </div>
  <div class="field">
    <%= f.label :xcf_gender %><br>
    <%= f.text_field :xcf_gender %>
  </div>
  <div class="field">
    <%= f.label :xcf_birthyear %><br>
    <%= f.text_field :xcf_birthyear %>
  </div>
  <div class="field">
    <%= f.label :xcf_birthplace %><br>
    <%= f.text_field :xcf_birthplace %>
  </div>
  <div class="field">
    <%= f.label :xcf_credit %><br>
    <%= f.text_field :xcf_credit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/xucf_students/edit.html.erb
<h1>Editing Xucf Student</h1>

<%= render 'form' %>

<%= link_to 'Show', xucf_class_xucf_student_path(@xucf_class, @xucf_student) %> |
<%= link_to 'Back', xucf_class_xucf_students_path(@xucf_class) %>

app/views/xucf_students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Xucf Students</h1>

<table>
  <thead>
    <tr>
      <th>Xcf no</th>
      <th>Xcf name</th>
      <th>Xcf class</th>
      <th>Xcf gender</th>
      <th>Xcf birthyear</th>
      <th>Xcf birthplace</th>
      <th>Xcf credit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @xucf_students.each do |xucf_student| %>
      <tr>
        <td><%= xucf_student.xcf_no %></td>
        <td><%= xucf_student.xcf_name %></td>
        <td><%= xucf_student.xucf_class_id %></td>
        <td><%= xucf_student.xcf_gender %></td>
        <td><%= xucf_student.xcf_birthyear %></td>
        <td><%= xucf_student.xcf_birthplace %></td>
        <td><%= xucf_student.xcf_credit %></td>
        <td><%= link_to 'Show', xucf_class_xucf_student_path(@xucf_class, xucf_student) %></td>
        <td><%= link_to 'Edit', edit_xucf_class_xucf_student_path(@xucf_class, xucf_student) %></td>
        <td><%= link_to 'Destroy',  xucf_class_xucf_student_path(@xucf_class, xucf_student), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Xucf student', new_xucf_class_xucf_student_path(@xucf_class) %>

app/views/xucf_students/new.html.erb
<h1>New Xucf Student</h1>

<%= render 'form' %>

<%= link_to 'Back', xucf_students_path %>

app/views/xucf_students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Xcf no:</strong>
  <%= @xucf_student.xcf_no %>
</p>

<p>
  <strong>Xcf name:</strong>
  <%= @xucf_student.xcf_name %>
</p>

<p>
  <strong>Xcf class:</strong>
  <%= @xucf_student.xucf_class_id %>
</p>

<p>
  <strong>Xcf gender:</strong>
  <%= @xucf_student.xcf_gender %>
</p>

<p>
  <strong>Xcf birthyear:</strong>
  <%= @xucf_student.xcf_birthyear %>
</p>

<p>
  <strong>Xcf birthplace:</strong>
  <%= @xucf_student.xcf_birthplace %>
</p>

<p>
  <strong>Xcf credit:</strong>
  <%= @xucf_student.xcf_credit %>
</p>

<%= link_to 'Edit', edit_xucf_class_xucf_student_path(@xucf_class, @xucf_student) %> |
<%= link_to 'Back', xucf_class_xucf_students_path(@xucf_class) %>