config/routes.rb
Rails.application.routes.draw do
  resources :reports, :as => :xucf_reports, :controller => :xucf_reports
  resources :class_courses, :as => :xucf_class_courses, :controller => :xucf_class_courses
  resources :courses, :as => :xucf_courses, :controller => :xucf_courses do
    member do
      get 'grade/:grade_id', :action => 'grade'
    end
  end
  resources :teachers, :as => :xucf_teachers, :controller => :xucf_teachers do
    member do
      get :courses
    end
  end
  resources :classes, :as => :xucf_classes, :controller => :xucf_classes do
    resources :students, :as => :xucf_students, :controller => :xucf_students do
      member do
        get :scores
        get :courses
        get 'term/:term_id', :action => 'term'
      end
    end
    member do
      get :courses
    end
  end
  resources :majors, :as => :xucf_majors, :controller => :xucf_majors do
    member do
      get 'rank/:grade_id', :action => 'rank'
    end
  end

end

app/controllers/xucf_classes_controller.rb
class XucfClassesController < ApplicationController
  before_action :set_xucf_class, only: [:show, :edit, :update, :destroy]

  def courses
    class_courses = XucfClassCourse.where( :xucf_class_id => params[:id] )
    @named_courses = []
    class_courses.each do |ccourse|
      course = XucfCourse.where( :id => ccourse[:xucf_course_id] ).first
      teacher = XucfTeacher.where( :id => ccourse[:xucf_teacher_id] ).first
      @named_courses << { course_name: course[:xcf_name], teacher_name: teacher[:xcf_name], term: ccourse[:xcf_term] }
    end
    respond_to do |format|
      format.json { render :json => @named_courses }
    end
  end

  # GET /xucf_classes
  # GET /xucf_classes.json
  def index
    @xucf_classes = XucfClass.all
  end

  # GET /xucf_classes/1
  # GET /xucf_classes/1.json
  def show
  end

  # GET /xucf_classes/new
  def new
    @xucf_class = XucfClass.new
  end

  # GET /xucf_classes/1/edit
  def edit
  end

  # POST /xucf_classes
  # POST /xucf_classes.json
  def create
    @xucf_class = XucfClass.new(xucf_class_params)

    respond_to do |format|
      if @xucf_class.save
        format.html { redirect_to @xucf_class, notice: 'Xucf class was successfully created.' }
        format.json { render :show, status: :created, location: @xucf_class }
      else
        format.html { render :new }
        format.json { render json: @xucf_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /xucf_classes/1
  # PATCH/PUT /xucf_classes/1.json
  def update
    respond_to do |format|
      if @xucf_class.update(xucf_class_params)
        format.html { redirect_to @xucf_class, notice: 'Xucf class was successfully updated.' }
        format.json { render :show, status: :ok, location: @xucf_class }
      else
        format.html { render :edit }
        format.json { render json: @xucf_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /xucf_classes/1
  # DELETE /xucf_classes/1.json
  def destroy
    @xucf_class.destroy
    respond_to do |format|
      format.html { redirect_to xucf_classes_url, notice: 'Xucf class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_xucf_class
      @xucf_class = XucfClass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def xucf_class_params
      params.require(:xucf_class).permit(:xcf_no, :xucf_major_id, :xcf_grade)
    end
end

app/helpers/xucf_classes_helper.rb
module XucfClassesHelper
end

app/views/xucf_classes/_form.html.erb
<%= form_for(@xucf_class) do |f| %>
  <% if @xucf_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@xucf_class.errors.count, "error") %> prohibited this xucf_class from being saved:</h2>

      <ul>
      <% @xucf_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :xcf_no %><br>
    <%= f.text_field :xcf_no %>
  </div>
  <div class="field">
    <%= f.label :xucf_major_id %><br>
    <%= f.number_field :xucf_major_id %>
  </div>
  <div class="field">
    <%= f.label :xcf_grade %><br>
    <%= f.text_field :xcf_grade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/xucf_classes/edit.html.erb
<h1>Editing Xucf Class</h1>

<%= render 'form' %>

<%= link_to 'Show', @xucf_class %> |
<%= link_to 'Back', xucf_classes_path %>

app/views/xucf_classes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Xucf Classes</h1>

<table>
  <thead>
    <tr>
      <th>Xcf no</th>
      <th>Xcf major</th>
      <th>Xcf grade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @xucf_classes.each do |xucf_class| %>
      <tr>
        <td><%= xucf_class.xcf_no %></td>
        <td><%= xucf_class.xucf_major_id %></td>
        <td><%= xucf_class.xcf_grade %></td>
        <td><%= link_to 'Show', xucf_class %></td>
        <td><%= link_to 'Edit', edit_xucf_class_path(xucf_class) %></td>
        <td><%= link_to 'Destroy', xucf_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Xucf class', new_xucf_class_path %>

app/views/xucf_classes/new.html.erb
<h1>New Xucf Class</h1>

<%= render 'form' %>

<%= link_to 'Back', xucf_classes_path %>

app/views/xucf_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Xcf no:</strong>
  <%= @xucf_class.xcf_no %>
</p>

<p>
  <strong>Xcf major:</strong>
  <%= @xucf_class.xucf_major_id %>
</p>

<p>
  <strong>Xcf grade:</strong>
  <%= @xucf_class.xcf_grade %>
</p>

<%= link_to 'Edit', edit_xucf_class_path(@xucf_class) %> |
<%= link_to 'Back', xucf_classes_path %>